import type { PersonalProfile, ScenarioAssumptions } from '../domain'

export const COMPACT_STATE_DEFAULTS_VERSION = 'de2026-2026-05-27'

interface CompactShareDefaults {
  profile: PersonalProfile
  assumptions: ScenarioAssumptions
}

export const COMPACT_SHARE_DEFAULTS_BY_VERSION: Record<string, CompactShareDefaults> = {
  [COMPACT_STATE_DEFAULTS_VERSION]: {
    profile: {
      age: 28,
      retirementAge: 67,
      grossSalaryYear: 75_000,
      taxClass: 1,
      childBirthYears: [],
      churchTax: false,
      publicHealthInsurance: true,
      healthAdditionalContributionPct: 2.9,
      pkvMonthlyPremium: 0,
      pPVMonthlyPremium: 0,
      desiredNetMonthlyPension: 0,
    },
    assumptions: {
      inflationRate: 0,
      retirementEndAge: 90,
      visibleProducts: ['etf', 'bav'],
      equalInputAmountEUR: 200,
      returnScenarios: [
        { id: 'konservativ', label: 'Konservativ', annualReturn: 0.03 },
        { id: 'basis', label: 'Basis', annualReturn: 0.05 },
        { id: 'optimistisch', label: 'Optimistisch', annualReturn: 0.07 },
      ],
      monteCarlo: {
        enabled: true,
        runs: 1_000,
        annualVolatility: 0.15,
        seed: 2026,
      },
      etf: {
        annualAssetFee: 0.002,
        equityPartialExemption: 0.3,
        annualContributionGrowthRate: 0,
      },
      bav: {
        monthlyGrossConversion: 200,
        statutoryMinimumSubsidyEnabled: true,
        contractualMatchPercent: 0,
        contractualFixedMonthly: 0,
        monthlyOtherRetirementIncome: 0,
        includeGrvReduction: false,
        kvdrMember: true,
        durchfuehrungsweg: 'direktversicherung_3_63',
        pre2005EligibleTaxFree: false,
        payoutMode: 'leibrente',
        rentenfaktor: 30,
        rentenfaktorConfirmed: false,
        zeitrenteYears: 20,
        annualContributionGrowthRate: 0,
        fees: {
          wrapperAssetFee: 0.003,
          fundAssetFee: 0.005,
          contributionFee: 0.03,
          fixedMonthlyFee: 0,
          acquisitionCostPct: 0.025,
          acquisitionCostSpreadYears: 5,
          pensionPayoutFeePct: 0,
        },
      },
      basisrente: {
        monthlyGrossContribution: 200,
        payoutMode: 'leibrente',
        rentenfaktor: 28,
        rentenfaktorConfirmed: false,
        monthlyOtherRetirementIncome: 0,
        fees: {
          wrapperAssetFee: 0.012,
          fundAssetFee: 0.002,
          contributionFee: 0.03,
          fixedMonthlyFee: 5,
          acquisitionCostPct: 0.025,
          acquisitionCostSpreadYears: 5,
          pensionPayoutFeePct: 0,
        },
      },
      statutoryPension: {
        pensionBaselineType: 'grv',
        manualMonthlyGross: null,
        currentEntgeltpunkte: 8,
        includeGrvReduction: false,
        annualSalaryGrowthRate: 0,
        rentenwertGrowthRate: 0,
        versorgungswerkMonthlyContribution: 0,
        versorgungswerkEmployerMonthly: 0,
        retirementHealthStatus: 'kvdr',
      },
      altersvorsorgedepot: {
        subtype: 'standarddepot',
        monthlyOwnContribution: 200,
        eligibility: {
          directlyEligible: true,
          indirectSpouseEligible: false,
          eligibleChildren: 0,
          ageAtContractStart: 28,
          careerStarterBonusUsed: true,
        },
        riskAllocationPct: 0.80,
        riskAnnualReturn: 0.05,
        lowRiskAnnualReturn: 0.02,
        fees: {
          wrapperAssetFee: 0.003,
          fundAssetFee: 0.002,
          contributionFee: 0,
          fixedMonthlyFee: 0,
          acquisitionCostPct: 0,
          acquisitionCostSpreadYears: 5,
          pensionPayoutFeePct: 0,
        },
        payoutMode: 'certified_payout_plan',
        payoutPlanEndAge: 85,
        partialCapitalPct: 0,
        transferCostEUR: 0,
        riesterTransferCapital: 0,
        monthlyOtherRetirementIncome: 0,
        rentenfaktor: 28,
      },
      riester: {
        monthlyOwnContribution: 200,
        existingCapital: 0,
        eligibility: {
          directlyEligible: true,
          ageAtContractStart: 28,
          careerStarterBonusUsed: false,
        },
        capitalGuarantee: {
          enabled: true,
          floorPctOfContributions: 1,
        },
        fees: {
          wrapperAssetFee: 0.012,
          fundAssetFee: 0.002,
          contributionFee: 0.03,
          fixedMonthlyFee: 5,
          acquisitionCostPct: 0.025,
          acquisitionCostSpreadYears: 5,
          pensionPayoutFeePct: 0,
        },
        payoutMode: 'leibrente',
        rentenfaktor: 28,
        rentenfaktorConfirmed: false,
        zeitrenteYears: 20,
        partialCapitalPct: 0,
        monthlyOtherRetirementIncome: 0,
      },
      insurance: {
        contractStartYear: 2024,
        oldContractTaxFreeEligible: false,
        monthlyOtherRetirementIncome: 0,
        capitalGuarantee: {
          enabled: true,
          floorPctOfContributions: 1,
        },
        payoutMode: 'leibrente',
        rentenfaktor: 28,
        rentenfaktorConfirmed: false,
        zeitrenteYears: 20,
        fees: {
          wrapperAssetFee: 0.003,
          fundAssetFee: 0.002,
          contributionFee: 0,
          fixedMonthlyFee: 3,
          acquisitionCostPct: 0.025,
          acquisitionCostSpreadYears: 5,
          pensionPayoutFeePct: 0.015,
        },
        surrenderHaircutPct: 0,
        annualContributionGrowthRate: 0,
      },
    },
  },
}
