// ---------------------------------------------------------------------------
// llmsTxt — generator for `dist/llms.txt` (issue #10).
//
// Pure function over the public-route registry. Mirrors `sitemap.ts` /
// `robots.ts`: deterministic byte-for-byte output for the same registry.
// The build pipeline (`scripts/prerender.mjs`) writes the result to
// `dist/llms.txt` after the SSG pass; the companion `dist/llms-full.txt`
// is generated by the script directly from prerendered HTML and is not the
// concern of this module.
//
// Format follows https://llmstxt.org:
//
//   # RentenWiki.de
//
//   > <purpose statement>
//
//   ## Rechner und Themen
//
//   - [<title>](<absolute-canonical-url>): <summary one-liner>
//
// One link entry per in-sitemap route, in registry source order. The /404
// route is excluded (consistent with sitemap.ts; not a citable page).
//
// Treated as experimental — see `docs/seo/llms-txt.md`.
// ---------------------------------------------------------------------------

import {
  PUBLIC_ROUTE_IDS,
  buildCanonicalUrl,
  publicRouteRegistry,
  type PublicRoute,
  type PublicRouteId,
} from './publicRouteRegistry'

/**
 * Site purpose statement embedded as the llms.txt blockquote header. Matches
 * the disclaimer posture (not advice, non-commercial license) and the 2026
 * statutory-data window. Kept in sync with the homepage meta description but
 * trimmed to a single sentence per llmstxt.org convention.
 */
export const LLMS_TXT_PURPOSE =
  'Kostenloser Modellrechner für die Altersvorsorge in Deutschland. ' +
  'Keine Steuer-, Rechts- oder Anlageberatung. ' +
  'Quelloffen, nicht-kommerziell (PolyForm Noncommercial 1.0.0). Stand 2026.'

/**
 * Heading for the route list section. German to match the rest of the site.
 */
export const LLMS_TXT_SECTION_HEADING = '## Rechner und Themen'

/**
 * Top-level heading. Brand name (RentenWiki.de) per CLAUDE.md.
 */
export const LLMS_TXT_TITLE = '# RentenWiki.de'

/**
 * Optional registry override for testing. Defaults to the production registry.
 *
 * When `routes` is supplied (custom registry), `routeIds` is widened to plain
 * strings so tests can pass synthetic keys; when omitted, `routeIds` is the
 * typed `PublicRouteId` union driven by the production registry.
 */
export interface LlmsTxtOptions {
  readonly routeIds?: readonly (PublicRouteId | string)[]
  readonly routes?: Readonly<Record<string, PublicRoute>>
}

/**
 * Collapse internal whitespace runs to single spaces. The registry's `summary`
 * fields are written with line breaks for readability; llms.txt entries need
 * one-liners so consumers can parse line-by-line.
 */
function collapseWhitespace(input: string): string {
  return input.replace(/\s+/g, ' ').trim()
}

/**
 * Generate `llms.txt` content from the public-route registry.
 *
 * Pure function — same input always produces byte-identical output. The
 * prerender script writes this string to `dist/llms.txt`.
 *
 * Decisions pinned in issue #10:
 *   - Only routes with `inSitemap: true` are listed (excludes `/404`).
 *   - URLs are canonical absolute URLs (no `?s=` share-state, no fragments).
 *   - Iteration order matches the registry's source order (homepage first).
 *   - Each entry is `- [title](url): summary` — title and summary read from
 *     the registry; summary whitespace is collapsed to a single line.
 */
export function generateLlmsTxt(options: LlmsTxtOptions = {}): string {
  const routeIds = options.routeIds ?? PUBLIC_ROUTE_IDS
  const registry = options.routes ?? publicRouteRegistry

  const lines: string[] = []
  lines.push(LLMS_TXT_TITLE)
  lines.push('')
  lines.push(`> ${LLMS_TXT_PURPOSE}`)
  lines.push('')
  lines.push(LLMS_TXT_SECTION_HEADING)
  lines.push('')

  for (const routeId of routeIds) {
    const entry = (registry as Record<string, PublicRoute>)[routeId]
    if (!entry) continue
    if (!entry.inSitemap) continue
    const url = options.routes
      ? buildAbsoluteUrl(entry.canonical)
      : buildCanonicalUrl(routeId as PublicRouteId)
    const summary = collapseWhitespace(entry.summary)
    lines.push(`- [${entry.title}](${url}): ${summary}`)
  }

  // Trailing newline — standard convention, keeps git diffs tidy.
  return lines.join('\n') + '\n'
}

/**
 * Fallback URL builder for tests that pass a custom registry override. Mirrors
 * `buildCanonicalUrl` but does not require the route key to be in the typed
 * `PublicRouteId` union.
 */
function buildAbsoluteUrl(canonical: string): string {
  // Lazy import to avoid a circular evaluation order at module load.
  // SITE_ORIGIN is a const string — safe to inline via the registry import.
  const origin = 'https://rentenwiki.de'
  if (canonical === '/') return origin + '/'
  return origin + canonical
}
